### 🔓 1. public 경로 테스트 (permitAll)
GET http://localhost:8080/index.html
Accept: text/html

###
GET http://localhost:8080/swagger/index.html
Accept: text/html


### 🔐 2. external 경로 테스트 (OAuth2 Mocked Token)
GET http://localhost:8080/external/sample
Authorization: Bearer mock-token
Accept: application/json

###

### 🔐 3. internal 경로 테스트 (Basic Auth)
GET http://localhost:8080/internal/sample
Authorization: Basic user:password
Accept: application/json


### ✅ internal - with Basic Auth
GET http://localhost:8080/internal/test
Authorization: Basic dXNlcjpwYXNzd29yZAo=
