### public 1
GET http://localhost:8080/index.html
Accept: text/html
### public 2
GET http://localhost:8080/swagger/index.html
Accept: text/html


### oauth
GET http://localhost:8080/external/sample
Authorization: Bearer mock-token
Accept: application/json
### oauth-fail
GET http://localhost:8080/external/any-foo-request
Accept: application/json


### basic-auth
GET http://localhost:8080/internal/sample
Authorization: Basic dXNlcjpwYXNzd29yZA==
### basic-auth-fail
GET http://localhost:8080/internal/any-foo-request
Authorization: Basic user:password
Accept: application/json

### others
GET http://localhost:8080/any
Accept: application/json
