openapi: 3.0.3
info:
  title: my sample
  description: my sample external
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: local

paths:
  /external/sample:
    get:
      summary: 외부용 샘플 API
      description: OAuth2 인증이 필요한 외부용 GET API
      tags:
        - External
      security:
        - oauth2: [ ]
      responses:
        '200':
          description: 성공 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: hello world

components:
  securitySchemes:
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: JWT
