openapi: 3.0.3
info:
  title: my sample
  description: my sample internal
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: local
tags:
  - name: internals
    description: 내부용 basic auth
paths:
  /internal/sample:
    get:
      summary: 내부용 샘플 API
      description: Basic 인증이 필요한 내부용 GET API
      tags:
        - Internal
      security:
        - basicAuth: []
      responses:
        '200':
          description: 성공 응답
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: hello world

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
